### ISSUE TITLE
Hardware Questions

### ISSUE THREAD

**Issue by Stewart-Michael-116** [gfvalvo/TeensyPOV#1]
Hello! I just have a couple of questions that I would be grateful if they were answered. 
1. Why is this project still considered a work in progress?
2. Also, Where did you get the blank blade with the hub connected? Did you build it?
Thank you for your help,
- Michael Stewart

**Comment by gfvalvo** [comment]
Hi, sorry for the delayed reply:

1. Because that's the nature of these types of DIY projects :)  There's always new features that can be added and tweaks that can be made.

2. The blade is made from a black PVC called Sintra. I got it from a friend who's business is working with plastics. I got the hub from Amazon: https://www.amazon.com/gp/product/B06Y6MSYCS/ref=ppx_yo_dt_b_asin_title_o05_s00?ie=UTF8&psc=1
